# Generated by Django 4.0.6 on 2022-07-22 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input_Image_URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date published')),
                ('image_url', models.CharField(max_length=100)),
            ],
        ),
    ]
